lookUpTable <- list("z"=list("label"="z", "unit_r"="", "unit_html"="", "val"="z"),
                    "a"=list("label"="a", "unit_r"="", "unit_html"="", "val"="a"),
                    "CoDist"=list("label"="Comoving Radial Distance LoS", "unit_r"="(Mpc)", "unit_html"="(Mpc)", "val"="CoDist"),
                    "LumDist"=list("label"="Luminosity Distance", "unit_r"="(Mpc)", "unit_html"="(Mpc)", "val"="LumDist"),
                    "AngDist"=list("label"="Angular Size Distance", "unit_r"="(Mpc)", "unit_html"="(Mpc)", "val"="AngDist"),
                    "CoDistTran"=list("label"="Comoving Radial Distance Tran", "unit_r"="(Mpc)", "unit_html"="(Mpc)", "val"="CoDistTran"),
                    "DistMod"=list("label"="Distance Modulus", "unit_r"="(mag)", "unit_html"="(mag)", "val"="DistMod"),
                    "AngSize"=list("label"="Angular Size", "unit_r"="(kpc/arcsec)", "unit_html"="(kpc/arcsec)", "val"="AngSize"),
                    "CoVol"=list("label"="Comoving Volume", "unit_r"="(Gpc^{3})", "unit_html"="(Gpc<sup>3</sup>)", "val"="CoVol"),
                    "HubTime"=list("label"="Hubble Time", "unit_r"="(Gyr)", "unit_html"="(Gyr)", "val"="HubTime"),
                    "UniAgeNow"=list("label"="Universe Age Now", "unit_r"="(Gyr)", "unit_html"="(Gyr)", "val"="UniAgeNow"),
                    "UniAgeAtz"=list("label"="Universe Age", "unit_r"="(Gyr)", "unit_html"="(Gyr)", "val"="UniAgeAtz"),
                    "TravelTime"=list("label"="Look-back Time", "unit_r"="(Gyr)", "unit_html"="(Gyr)", "val"="TravelTime"),
                    "H"=list("label"="H", "unit_r"="(Km/s / Mpc)", "unit_html"="(Km/s / Mpc)", "val"="H"),
                    "OmegaM"=list("label"="OmegaM", "unit_r"="", "unit_html"="", "val"="OmegaM"),
                    "OmegaL"=list("label"="OmegaL", "unit_r"="", "unit_html"="", "val"="OmegaL"),
                    "OmegaK"=list("label"="OmegaK", "unit_r"="", "unit_html"="", "val"="OmegaK"),
                    "Factor"=list("label"="Growth Factor", "unit_r"="", "unit_html"="", "val"="Factor"),
                    "Rate"=list("label"="Growth Rate", "unit_r"="", "unit_html"="", "val"="Rate"),
                    "RhoCrit"=list("label"="Critical Mass Density", "unit_r"="(10^{10}*Msol/Mpc^{3})", "unit_html"="(10<sup>10</sup>Msol/Mpc<sup>3</sup>)", "val"="RhoCrit")
)