lookUpTable <- list("z"=list("label"="z", "unit"="", "val"="z"),
                    "a"=list("label"="a", "unit"="", "val"="a"),
                    "CoDist"=list("label"="Comoving Radial Distance LoS", "unit"="(Mpc)", "val"="CoDist"),
                    "LumDist"=list("label"="Luminosity Distance", "unit"="(Mpc)", "val"="LumDist"),
                    "AngDist"=list("label"="Angular Size Distance", "unit"="(Mpc)", "val"="AngDist"),
                    "CoDistTran"=list("label"="Comoving Radial Distance Tran", "unit"="(Mpc)", "val"="CoDistTran"),
                    "DistMod"=list("label"="Distance Modulus", "unit"="(mag)", "val"="DistMod"),
                    "AngSize"=list("label"="Angular Size", "unit"="(kpc/arcsec)", "val"="AngSize"),
                    "CoVol"=list("label"="Comoving Volume", "unit"="(Gpc³)", "val"="CoVol"),
                    "HubTime"=list("label"="Hubble Time", "unit"="(Gyr)", "val"="HubTime"),
                    "UniAgeNow"=list("label"="Universe Age Now", "unit"="(Gyr)", "val"="UniAgeNow"),
                    "UniAgeAtz"=list("label"="Universe Age", "unit"="(Gyr)", "val"="UniAgeAtz"),
                    "TravelTime"=list("label"="Look-back Time", "unit"="(Gyr)", "val"="TravelTime"),
                    "H"=list("label"="H", "unit"="(Km/s / Mpc)", "val"="H"),
                    "OmegaM"=list("label"="OmegaM", "unit"="", "val"="OmegaM"),
                    "OmegaL"=list("label"="OmegaL", "unit"="", "val"="OmegaL"),
                    "OmegaK"=list("label"="OmegaK", "unit"="", "val"="OmegaK"),
                    "Factor"=list("label"="Growth Factor", "unit"="", "val"="Factor"),
                    "Rate"=list("label"="Growth Rate", "unit"="", "val"="Rate"),
                    "RhoCrit"=list("label"="Critical Mass Density", "unit"="(10<sup>10</sup>Msol/Mpc<sup>3</sup>)", "val"="RhoCrit")
)